config/routes.rb
Rails.application.routes.draw do
  
  resources :leaderboards, only: [:index]

  resource :sessions, only: [:new, :create, :destroy]

  resources :pictures, :collection => { :destroy_multiple => :delete}

  resources :users

  root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
	has_attached_file :pic, :styles => { :display => "x500", :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, :attributes => :pic, :less_than => 1.megabytes
end

## when date.now is more than 24 hours, delete it. 

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  has_secure_password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
  	User.where(id: session["user_id"]).first
  end
  
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  def index
  	@posts = Picture.all.order(:score).reverse_order
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    if Picture.count >= 2
      @picture = Picture.all
      prng = Random.new
      a = @picture[prng.rand(Picture.count)]
      b = @picture[prng.rand(Picture.count)]
      if a != b
        @rand_pic = a
        @rand_pic2 = b
      else
        redirect_to pictures_path
      end

    else
      redirect_to new_picture_path 
    end
    # a better way to do rand pic:

    puts "=================="
    puts Picture.count
    puts @rand_pic
    puts @rand_pic2
    puts "=================="
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def create
    if current_user != nil
      picture = Picture.new(params.require(:picture).permit(:pic, :caption, :score))
      if picture.save
        redirect_to pictures_path
      else
        # TODO - This should redirect to an error page if the image isn't saved. The reason it won't save is because it is over 1MB. 
        redirect_to pictures_path
      end
    else
      redirect_to new_sessions_path
    end
  end

  def edit
  end

  def update
    pict = Picture.where(id: params[:id]).first
    # raise params.inspect
    pict.increment(:score)
    if pict.save
      redirect_to pictures_path
    else
      raise params.inspect
    end
    # if 
    # pict = Picure.update(params.require(:pic).permit(:pic, :caption, :score))
    #     picture = Picture.find(params[:id])
    #     (params.require(:picture).permit(:pic, :caption, :score))
    # end
    # if picture.save
    #   redirect_to pictures_path
    # end
  end

  def destroy
  end

  def destroy_multiple
      @toBeDeleted = Picture.where("created_at <= ?", Time.now - 24.hours)
      if @toBeDeleted.destroy_all
        redirect_to leaderboards_path
      else
        raise params.inspect
      end
  end


  # private
  #   def user_params
  #     params.require(:picture).permit(:pic, :caption, :score)
  #   end
end

# THIS WORKS:

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
  	puts "=========================================="
  	puts params.inspect
  	puts "=========================================="
    u = User.where(username: params[:user][:username]).first
    if u != nil && u.authenticate(params[:user][:password])
      session["user_id"] = u.id.to_s
      redirect_to pictures_path(user_id: u.id)
    else
      redirect_to new_sessions_path
    end
  end

  def destroy
    session.destroy
    redirect_to pictures_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @currentUser = User.where(id: session["user_id"]).first

  end

  def new
    @user = User.new
  end

  def create
    user = User.new(params.require(:user).permit(:username, :avatar, :password, :password_digest))
    if user.save
      session['user_id'] = user.id.to_s
      redirect_to pictures_path
    else
      redirect_to new_user_path
    end
  end

  def edit
  end

  def destroy
    @user = User.where(id: params[:id]).first
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leadboards_helper.rb
module LeadboardsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P22</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Playfair+Display+SC:900,400,900italic,400italic' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="container">

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>

        </button>
        <a class="navbar-brand" class="navTitle">Picture Competition</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', pictures_path %></li>
          <li><%= link_to 'Leaderboard', leaderboards_path %></li>
    

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'All Users', users_path %></li> 

            <% if current_user != nil %>
              <li>
              <a href="#">Welcome, <%= current_user.username %>.</a></li>
              <li><%= link_to "log out", sessions_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "sign up", new_user_path, method: :get %></li>
              <li><%= link_to "log in", new_sessions_path %></li>
            <% end %>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="content">
<%= yield %>
  </div>
</body>
</html>

app/views/leaderboards/index.html.erb
<h1 class="titled"><i>The Top 100</i></h1>
<table class="myTable">
	<thead>
		<tr class="tableHeader">
			<th class="tableData1">Picture</th>
			<th class="tableData2">Points</th>
			<th class="tableData3">Caption</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |p| %>
		<tr class="tableHeader">
			<td class="tableData1"><%= image_tag p.pic.url(:medium) %></td>
			<td class="tableData22"><%= p.score %></td>
			<td class="tableData33"><%= p.caption %></td>
		</tr>
		<% end %>
	</tbody>
<%#= link_to "Cast your vote!", :url => destroy_multiple_pictures_path, :class => 'btn btn-primary' %>
<%#= link_to "Cast your vote!", picture_path(@rand_pic2), method: :patch, :class => 'btn btn-primary' %>

app/views/pictures/edit.html.erb
<h1>Pictures#edit</h1>
<p>Find me in app/views/pictures/edit.html.erb</p>

app/views/pictures/index.html.erb
<h1 class="titled"><i>Picture Competition</i></h1>

<!-- <div class="content"> -->
	<div class="all">
		<div class="gameboard">
			<div class="row">
				<div class="gamePiece">
					<div class="thumbnail">
						<%= image_tag @rand_pic.pic.url(:display) %>
						<div class="caption">
							<p><%= @rand_pic.caption %></p>
							<p id="score1" class="score"><%= @rand_pic.score %></p>
						</div>
						<%= link_to "Cast your vote!", picture_path(@rand_pic), method: :patch, :class => 'btn btn-primary' %>

					</div>
				</div>
			<div class="gamePiece">
				<div class="thumbnail">
					<%= image_tag @rand_pic2.pic.url(:display) %>				
					<div class="caption">
						<p><%= @rand_pic2.caption %></p><br>
						<p id="score2" class="score"><%= @rand_pic2.score %></p>
						<%= link_to "Cast your vote!", picture_path(@rand_pic2), method: :patch, :class => 'btn btn-primary' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="thirdRow">
	<% if current_user != nil %>
	<%= link_to "Upload your own!", new_picture_path, :class => 'btn btn-primary' %>
	<% else %>
	<%= link_to "Upload your own!", new_sessions_path, :class => 'btn btn-primary' %>
	<% end %>
	<%= link_to "Top 100!", leaderboards_path, :class => 'btn btn-primary' %>
</div>

<!-- </div> -->
<script>
//this doesn't work. Ideally I'll figure it out soon to avoid having to reload the page. 	
var numScore = $( "#score1" ).text()
parseInt(numScore);
console.log("Score: " + numScore);

var pic_id = <%= @rand_pic.id %>;
console.log("Pic Id: " + pic_id);

function incrementer(){
	console.log("clicked");
	numScore++;
	console.log("New Score: " + numScore);
	$.ajax({
		//URL for request:
		url: "pictures/" + pic_id,
		//Data to be sent:
		data: { score: numScore },
		type: "PATCH",
		//Type of data we expect back?
		//Success function:
		success: function(response, textStatus, jqXhr) {
			console.log("The following error occured: " + textStatus, errorThrown);
		},
		complete: function() {
			console.log("Score Put Ran");
		},
		error: function( xhr, status, errorThrown ){
			console.log( "There was a problem" );
			console.log( "Error: " + errorThrown );
			console.log( "Status: " + status );
			console.dir( xhr );
		}
	});

}


	// $.get( 'pictures/' + pic_id, {score : numScore}, function(){
	// 	console.log( "success" );
	// })
	// .done(function(){
	// 	console.log( "second success" );
	// })
	// .fail(function(){
	// 	console.log( "error" );
	// })
	// .always(function(){
	// 	console.log( "finished" );
	// });
</script>

app/views/pictures/new.html.erb
<h1>Add a new picture</h1>

		<%= bootstrap_form_for @picture, :url => pictures_path, :html => { :multipart => true } do |f| %>


			<div class="field">
			<%= f.file_field :pic, help: "Must be under 1 MB" %>
			</div><br><br>
			<div class="field">
			<%= f.text_field :caption %>
			</div><br><br>
			<%= f.submit %>
		<% end %>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @user.each do |u| %>
	<%= u.username %><br>
	<%= image_tag u.avatar.url(:medium) %><br>
	<%= link_to 'profile', u %><br>
<% end %>	
<div class="thirdRow">

	<% if current_user != nil %>
	<%= link_to "Add a new user!", new_user_path, :class => 'btn btn-primary' %>
	<% else %>
	<%= link_to "Add a new user!!", new_user_path, :class => 'btn btn-primary' %>
	<% end %>

</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= bootstrap_form_for @user, validate: :true, :url => users_path, :html => { :multipart => true } do |f| %>
	<%= f.text_field :username, help: "Must be under 50 characters" %><br />
	<%= f.password_field :password, help: "must be at least 8 characters long" %><br />
	<%= f.password_field :password_confirmation %>
	<%= f.file_field :avatar %><br />
	<%= yield(:user_validators) %>
	<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @currentUser.username %>'s Profile</h1><br>
<%= image_tag @currentUser.avatar.url(:medium) %><br>
<%= link_to 'back to the menu', users_path %><br>


<%= link_to ' Delete', @currentUser, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %>